### ISSUE TITLE
Hires fix and batch are not part of the clipboard prompt recall feature

### ISSUE THREAD

**Issue by fiveseven808** [Kilvoctu/aiyabot#155] opened 2023-03-23 07:24 UTC
If I try to add hires or batch to a prompt, it's not in the list of things captured by the clipboard button, nor does it populate in the prompt. 

I'm not even entirely sure hires fix does anything with this bot, but I thought I'd point it out. 

Steps to replicate:
1. /draw something with a hires_fix:something or batch:something
2. Click on the clipboard button 

"Command for copying" does not contain hires fix or batch, nor is it listed anywhere else. 

Batch doesn't show up either but I saw something about a line in the config file. I set it to true but I haven't noticed a change in behavior, however I did not restart the bot, I just did a /settings refresh:true

**Comment by Kilvoctu** [comment] 2023-03-23 15:55
Heya, the hires fix works for AIYA. You can try same parameters with, and without, hires fix and cross reference by running the same tasks in the Web UI. This feature has been tested in servers that run the aiyabot.

As far the 📋, this pulls the png info that the Web UI itself creates for each image. It then parses said info and makes the fancy embed.  
When using Web UI's compatibility option for the old hires fix, there does seem to be a bug in which Web UI does not fill in the png info properly (this bug does not affect new hires fix... I logged a bug report on Web UI repo  
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8837  

With the batch information, I believe Automatic1111 decided to remove that from the png info. The png info used to show like, batch size, batch position, etc, but it was removed. The reason is because the seed and other parameters are enough to reproduce any given image from a batch.  
Using 📋 on a batch is not going to work properly anyways (this [project](https://github.com/users/Kilvoctu/projects/3)). For copy command on batches currently t[he context menu](https://github.com/Kilvoctu/aiyabot/wiki/Context-menu-commands#get-image-info) is intended.

In any case, the missing hires fix png info is a bug on Web UI's side, not AIYA. For batch info, even if it was included, it's redundant information.  
When the bug is fixed on Web UI side, it should automatically work for AIYA (in the code, she is already looking for it in the png info). I think I may do some temporary workaround, but the issue is on Web UI.

**Comment by Kilvoctu** [comment] 2023-04-01 21:27
Gonna close this as there isn't anything I'll be doing, as mentioned above (I won't making any workaround).  
Also, Discord seemingly broke something in the last week #161, so 📋 is not currently working anyway.

**Closed by Kilvoctu** 2023-04-01 21:27 UTC
Labels: wontfix
