### ISSUE TITLE
I can't launch the bot, it closes it instantly

### ISSUE THREAD

**Issue by chans12** [Kilvoctu/aiyabot#164] opened 2023-04-09 06:26 UTC
**Describe the bug**  
I can't launch the bot, it closes it instantly
---

**Environment**
 - OS: Windows

---

**Console logs**  
![image](https://user-images.githubusercontent.com/104153996/230758028-42e69888-2eb7-49b5-803f-d5445fe0464a.png)

**Comment by Kilvoctu** [comment] 2023-04-09 06:50
Heya, looks like the repo wasn't cloned properly or something. Please try deleting the files and cloning the repo again.

**Comment by chans12** [comment] 2023-04-09 07:01
i tried it once, i cloned it again it was working but after adding some models and changing some configuration settings, its not working now

**Comment by Kilvoctu** [comment] 2023-04-09 07:29
> after adding some models and changing some configuration settings, its not working now

Can you give some more information on how to replicate the issue? This isn't enough for me to troubleshoot what may be the cause. Also, what Python version are you on?

**Comment by chans12** [comment] 2023-04-09 07:36
yeah sure, like i said after my first download failed i cloned and start to use it again, it was working and then i added 1 model, still working but after 2-3 and few configuration changes. I couldn't launch it again. When i click launch.bat cmd Immediately crashes.

Python version 3.10.6

**Comment by Kilvoctu** [comment] 2023-04-09 07:50
You are following the wiki guide? https://github.com/Kilvoctu/aiyabot/wiki/Model-swapping

Note that any line that doesn't have activator token still needs to be formatted correctly
example:
```
display_name|model_full_name|activator_token
SD 1.5|v1-5-pruned-emaonly
```
will crash because there is no `|` after the model name

**Comment by chans12** [comment] 2023-04-09 07:54
```
Sd15|v2-1_768-ema-pruned.safetensors|
Yesmixv15|yesmix_v15.safetensors|
HighQualityCGMIXV1|highQualityCGMIX_v1.safetensors|
```


oh i see but mine is like this, whats wrong with it?

**Comment by chans12** [comment] 2023-04-09 08:02
also its out of topic but, why can't i add SD 2.1 as a model? i can't see it thru the discord bot that i made

**Comment by Kilvoctu** [comment] 2023-04-09 08:17
> wow, i just fixed it , its because of i added a `negative_prompt_prefix = [example, example1]` looks like this after i deleted them, it launched

There is an example in the config.toml comments for the proper syntax  
`Separate with commas; example, ["a", "b", "c"]`

They need to be comma separated and within quotation marks ""

**Comment by Kilvoctu** [comment] 2023-04-09 08:18
> also its out of topic but, why can't i add SD 2.1 as a model? i can't see it thru the discord bot that i made

Please read carefully the guide https://github.com/Kilvoctu/aiyabot/wiki/Model-swapping#adding-models. I suspect you removed the first line `display_name|model_full_name|activator_token`? The guide mentions that line must stay there.

**Comment by chans12** [comment] 2023-04-09 08:18
i forgot about the comma yea, thank you

**Comment by Kilvoctu** [comment] 2023-04-09 18:14
I'm going to go ahead and close this as we resolved the original issue. If there's anything else, you can open another report or ask in Discussions 👍👍

**Closed by Kilvoctu** 2023-04-09 18:14 UTC
Labels: bug

**Comment by chans12** [comment] 2023-04-13 05:47
ca you give me your discord, i need help for something

**Comment by Kilvoctu** [comment] 2023-04-13 21:50
My contact is in the Wiki: https://github.com/Kilvoctu/aiyabot/wiki/Contact

I'm not too active on the Discord lately, so unless it's something information sensitive, it might actually be faster to help you here.

**Comment by chans12** [comment] 2023-04-15 06:24
i have multiple questions so, i don't think i can type all of it here. Would be good if i can add you :)
