### ISSUE TITLE
Bot restarted message on newly generated images when clicking on clipboard function 

### ISSUE THREAD

**Issue by fiveseven808** [Kilvoctu/aiyabot#158] opened 2023-03-29 06:04 UTC
Running Auto1111 Commit:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3856ada5cc9ac4124e20ff311ce7aa77330845d9

In some channels/threads in discord, when clicking on the clipboard icon on an image, the bot returns a:
"I may have been restarted. This button no longer works.
You can get the image info from the context menu or /identify"

Not all images have this issue, it seems to be channel/thread specific. 

This is not the usual case however, as the other 3 buttons continue to work for that image. 

Since the only thing that has changed for me is the Auto1111 commit, it might be on their end, but I thought I'd bring it up.

**Comment by Kilvoctu** [comment] 2023-03-29 07:14
I'm on Web UI currently latest commit https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81. I can't replicate this issue. I need more information as I don't know where to start troubleshooting.

What does it say in console log? What's different in those channels in which 📋 is failing? Does it affect all images in those channels or just some?

**Comment by Kilvoctu** [comment] 2023-04-01 21:36
Going to close this, since I created #161 which has a bit more information on possible root cause.  

It's interesting since at the time of my post above, it was working for me, so it was probably some slow rollout Discord did that hit you first (my test server is very tiny). If you can find any scenarios in which 📋 works, please put it in the other post as I'd like to know.

**Closed by Kilvoctu** 2023-04-01 21:36 UTC
Labels: bug, waiting for feedback
